// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsLw1nefn6xWg1rzEU5zcZVrbhNdgNyQc',
    appId: '1:302075601219:web:f51da0e46677daaa9acff6',
    messagingSenderId: '302075601219',
    projectId: 'qari-d7040',
    authDomain: 'qari-d7040.firebaseapp.com',
    storageBucket: 'qari-d7040.firebasestorage.app',
    measurementId: 'G-RREP91FKN8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuFW6Y4jnFnOyIjZW5r4PPHFWGQeil-Hw',
    appId: '1:302075601219:android:2f89aa284481949c9acff6',
    messagingSenderId: '302075601219',
    projectId: 'qari-d7040',
    storageBucket: 'qari-d7040.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdJtJCM3Ry54cdJ8taDvRgKqVXJLLzmLs',
    appId: '1:302075601219:ios:714ca3184ee2cfcb9acff6',
    messagingSenderId: '302075601219',
    projectId: 'qari-d7040',
    storageBucket: 'qari-d7040.firebasestorage.app',
    iosBundleId: 'kz.dudi.qari',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdJtJCM3Ry54cdJ8taDvRgKqVXJLLzmLs',
    appId: '1:302075601219:ios:714ca3184ee2cfcb9acff6',
    messagingSenderId: '302075601219',
    projectId: 'qari-d7040',
    storageBucket: 'qari-d7040.firebasestorage.app',
    iosBundleId: 'kz.dudi.qari',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsLw1nefn6xWg1rzEU5zcZVrbhNdgNyQc',
    appId: '1:302075601219:web:4b002d5889c2f9be9acff6',
    messagingSenderId: '302075601219',
    projectId: 'qari-d7040',
    authDomain: 'qari-d7040.firebaseapp.com',
    storageBucket: 'qari-d7040.firebasestorage.app',
    measurementId: 'G-W1C2XK493V',
  );
}
